[package]
name = "servarr-resources"
version = "0.1.0"
edition.workspace = true

[dependencies]
kube.workspace = true
k8s-openapi.workspace = true
serde.workspace = true
serde_json.workspace = true
servarr-crds.workspace = true
sha2 = "0.10.9"
tracing.workspace = true
