{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: servarr-operator-validating
  labels:
    app.kubernetes.io/name: servarr-crds
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.operatorNamespace }}/servarr-operator-webhook
webhooks:
  - name: validate.servarrapp.servarr.dev
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: servarr-operator-webhook
        namespace: {{ .Values.operatorNamespace }}
        path: /validate-servarrapp
    rules:
      - apiGroups:
          - servarr.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servarrapps
    failurePolicy: Fail
    sideEffects: None
{{- end }}
